## Presentation 3
**Question 7.2.9:** Write a naive Gaussian elimination code and use it to solve the sysrem of equations $Ax = b\$ where

\begin{equation}
A =
\begin{bmatrix}
1 & 1/2 & 1/3\\
1/2 & 1/3 & 1/4 \\
1/3 & 1/4 & 1/5
\end{bmatrix}
\end{equation}

and $b = \left[7/6, 5/6, 13/20\right]^T$.  The correct answer is $x = \left[0, 1, 2\right]^T$.

In [1]:
import math
import numpy as np

In [14]:
def guassian_elim_pp(A_, b_):
    A = np.copy(A_)
    b = np.copy(b_)
    n = A.shape[0]
    for i in range(n-1):
        am = abs(A[i,i])
        p = i
        for j in range(i+1, n):
            if abs(A[j,i]) > am:
                am = abs(A[j,i])
                p = j
        if p > i:
            for k in range(i, n):
                hold = A[i,k]
                A[i,k] = A[p,k]
                A[p,k] = hold
            hold = b[i]
            b[i] = b[p]
            b[p] = hold
        for j in range(i+1, n):
            m = A[j,i]/A[i,i]
            for k in range(i+1, n):
                A[j,k] = A[j,k] - m*A[i,k]
            b[j] = b[j] - m*b[i]
            
    n = A.shape[0]
    x = np.zeros(n)
    x[n - 1] = b[n - 1]/A[n - 1, n - 1]
    for i in range(n-1, 0, -1):
        sum_ = 0
        for j in range(i+1, n):
            sum_ = sum_ + A[i,j]*x[j]
        x[i] = (b[i] - sum_)/A[i,i]
    return A, b, x 

In [16]:
A = np.array([[1, 1/2, 1/3],
              [1/2, 1/3, 1/4],
              [1/3, 1/4, 1/5]])
b = np.array([7/6, 5/6, 13/20])
A_, b_, x = guassian_elim_pp(A, b)

In [17]:
print(np.array_str(x, precision=2, suppress_small=True))

[0. 1. 2.]


In [18]:
if((A@x).all() == b.all()):
    print(np.array_str(A@x, precision=2, suppress_small=True))
    print(np.array_str(b, precision=2, suppress_small=True))

[1.17 0.83 0.65]
[1.17 0.83 0.65]


In [19]:
A

array([[1.        , 0.5       , 0.33333333],
       [0.5       , 0.33333333, 0.25      ],
       [0.33333333, 0.25      , 0.2       ]])